/**
 * API Client Configuration for API Key Authentication
 *
 * This module configures the API client to automatically add API key headers
 * for endpoints that require API key authentication (e.g., specialists, user provisioning).
 *
 * The `src/client` directory is auto-generated by HeyAPI and should not be modified directly.
 * Instead, we configure the client using interceptors.
 */

import { client } from "@/client/client.gen";

/**
 * List of API endpoints that require API key authentication.
 * These endpoints use X-API-KEY header instead of Bearer token.
 */
const API_KEY_ENDPOINTS = ["/api/v1/specialists", "/api/v1/user-provisions"] as const;

/**
 * Get API key from environment variables (server-side only).
 */
function getApiKey(): string | undefined {
  if (typeof process !== "undefined") {
    return process.env.API_SERVICE_KEY;
  }
  return undefined;
}

/**
 * Get API key header name from environment variables.
 * Defaults to "X-API-KEY" if not specified.
 */
function getApiKeyHeaderName(): string {
  if (typeof process !== "undefined") {
    return process.env.API_KEY_HEADER_NAME || "X-API-KEY";
  }
  return "X-API-KEY";
}

/**
 * Check if a URL requires API key authentication.
 */
function requiresApiKey(url: string): boolean {
  return API_KEY_ENDPOINTS.some((endpoint) => url.includes(endpoint));
}

/**
 * Configure API key interceptor.
 * This should be called once during app initialization (server-side).
 */
export function configureApiKeyInterceptor(): void {
  const apiKey = getApiKey();
  const headerName = getApiKeyHeaderName();

  if (!apiKey) {
    console.warn(
      "[API Client] API_SERVICE_KEY not found in environment. " +
        "API requests requiring API key authentication may fail.",
    );
    return;
  }

  // Add request interceptor to inject API key for specific endpoints
  client.interceptors.request.use((request) => {
    const url = request.url;

    // Check if this endpoint requires API key
    if (requiresApiKey(url)) {
      request.headers.set(headerName, apiKey);
      console.log(`[API Client] ✓ API key added for: ${url}`);
    }

    return request;
  });

  console.log("[API Client] API key interceptor configured");
}
