/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMedicationsRouteImport } from './routes/dashboard/medications'
import { Route as DashboardHealthMetricsRouteImport } from './routes/dashboard/health-metrics'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as AuthSocialCallbackRouteImport } from './routes/auth/social-callback'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up.index'
import { Route as AuthSignUpUserDataRouteImport } from './routes/auth/sign-up.user-data'
import { Route as AuthSignUpPaymentInfoRouteImport } from './routes/auth/sign-up.payment-info'
import { Route as AuthCallbackStripeRouteImport } from './routes/auth/callback.stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicationsRoute = DashboardMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHealthMetricsRoute = DashboardHealthMetricsRouteImport.update({
  id: '/health-metrics',
  path: '/health-metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSocialCallbackRoute = AuthSocialCallbackRouteImport.update({
  id: '/social-callback',
  path: '/social-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpUserDataRoute = AuthSignUpUserDataRouteImport.update({
  id: '/sign-up/user-data',
  path: '/sign-up/user-data',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpPaymentInfoRoute = AuthSignUpPaymentInfoRouteImport.update({
  id: '/sign-up/payment-info',
  path: '/sign-up/payment-info',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackStripeRoute = AuthCallbackStripeRouteImport.update({
  id: '/callback/stripe',
  path: '/callback/stripe',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/health-metrics': typeof DashboardHealthMetricsRoute
  '/dashboard/medications': typeof DashboardMedicationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/stripe': typeof AuthCallbackStripeRoute
  '/auth/sign-up/payment-info': typeof AuthSignUpPaymentInfoRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/health-metrics': typeof DashboardHealthMetricsRoute
  '/dashboard/medications': typeof DashboardMedicationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/stripe': typeof AuthCallbackStripeRoute
  '/auth/sign-up/payment-info': typeof AuthSignUpPaymentInfoRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/social-callback': typeof AuthSocialCallbackRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/health-metrics': typeof DashboardHealthMetricsRoute
  '/dashboard/medications': typeof DashboardMedicationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/stripe': typeof AuthCallbackStripeRoute
  '/auth/sign-up/payment-info': typeof AuthSignUpPaymentInfoRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/social-callback'
    | '/dashboard/appointments'
    | '/dashboard/health-metrics'
    | '/dashboard/medications'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/auth/callback/stripe'
    | '/auth/sign-up/payment-info'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/social-callback'
    | '/dashboard/appointments'
    | '/dashboard/health-metrics'
    | '/dashboard/medications'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard'
    | '/api/auth/$'
    | '/auth/callback/stripe'
    | '/auth/sign-up/payment-info'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/social-callback'
    | '/dashboard/appointments'
    | '/dashboard/health-metrics'
    | '/dashboard/medications'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/auth/callback/stripe'
    | '/auth/sign-up/payment-info'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medications': {
      id: '/dashboard/medications'
      path: '/medications'
      fullPath: '/dashboard/medications'
      preLoaderRoute: typeof DashboardMedicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/health-metrics': {
      id: '/dashboard/health-metrics'
      path: '/health-metrics'
      fullPath: '/dashboard/health-metrics'
      preLoaderRoute: typeof DashboardHealthMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/social-callback': {
      id: '/auth/social-callback'
      path: '/social-callback'
      fullPath: '/auth/social-callback'
      preLoaderRoute: typeof AuthSocialCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up/user-data': {
      id: '/auth/sign-up/user-data'
      path: '/sign-up/user-data'
      fullPath: '/auth/sign-up/user-data'
      preLoaderRoute: typeof AuthSignUpUserDataRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up/payment-info': {
      id: '/auth/sign-up/payment-info'
      path: '/sign-up/payment-info'
      fullPath: '/auth/sign-up/payment-info'
      preLoaderRoute: typeof AuthSignUpPaymentInfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback/stripe': {
      id: '/auth/callback/stripe'
      path: '/callback/stripe'
      fullPath: '/auth/callback/stripe'
      preLoaderRoute: typeof AuthCallbackStripeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSocialCallbackRoute: typeof AuthSocialCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCallbackStripeRoute: typeof AuthCallbackStripeRoute
  AuthSignUpPaymentInfoRoute: typeof AuthSignUpPaymentInfoRoute
  AuthSignUpUserDataRoute: typeof AuthSignUpUserDataRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSocialCallbackRoute: AuthSocialCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCallbackStripeRoute: AuthCallbackStripeRoute,
  AuthSignUpPaymentInfoRoute: AuthSignUpPaymentInfoRoute,
  AuthSignUpUserDataRoute: AuthSignUpUserDataRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardHealthMetricsRoute: typeof DashboardHealthMetricsRoute
  DashboardMedicationsRoute: typeof DashboardMedicationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardHealthMetricsRoute: DashboardHealthMetricsRoute,
  DashboardMedicationsRoute: DashboardMedicationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
